export { initializeCanvas } from './factory'
export { stroke, fill, fillRGB, fillCanvas } from './canvas'
export { circle, ellipse } from './ellipse'
export { line } from './line'
export type { CanvasInfo, DrawFunction, Color } from './types'
